version: '3'

volumes:
  food_pg_data:
  static_volume:
  media_volume:

services:

  foodgram_bd:
    image: postgres:13.0-alpine
    env_file: .env
    volumes:
      - food_pg_data:/var/lib/postgresql/data/
    restart: always

  backend:
    image: saida3232/foodgram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media_volume:/media
    depends_on:
      - foodgram_bd
    restart: always

  frontend:
    image: saida3232/foodgram_frontend
    volumes:
      - static_volume:/static
    command: cp -r /app/build/. /static/

  nginx:
    container_name: nginx
    image: nginx:1.19.3
    ports:
      -  "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/usr/share/nginx/html
      - media_volume:/var/html/media/
    depends_on:
      - backend
      - frontend
