# Generated by Django 3.2.3 on 2024-05-05 17:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0003_auto_20240505_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='RecipeIngredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_recipe', to='foodgram.ingredient', validators=[django.core.validators.MinValueValidator(1, message='Минимальное количество 1!')], verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Время должно быть больше 1 минуты.')], verbose_name='Время готовки'),
        ),
    ]
